### ISSUE TITLE
How to resolve 429 too many requests?

### ISSUE THREAD

**Issue by lolifamily** [warp-plus-cloudflare/cli#1]

**Comment by ALIILAPRO** [comment]
> _No description provided._

The proxy function has been temporarily added to the Python code.

**Comment by lolifamily** [comment]
Seems that changing IP cannot resolve this problem

**Comment by lolifamily** [comment]
@ALIILAPRO

**Comment by lolifamily** [comment]
After adding 1200GB this account cannot add further, but changing an account can add
